### ISSUE TITLE
Typo in 2.3.1 Research area/discipline

### ISSUE THREAD

**Issue by mpfl** [au-research/hesanda-metadata-profile#28]
2.3.1 Research area/discipline currently reads:

Controlled vocabulary source: HeSANDA requires at least one ANZSRC FoR code.

Should read:

Notes: HeSANDA requires at least one ANZSRC FoR code.

**Comment by amandatombolatoardc** [comment]
This is a test

**Comment by amandatombolatoardc** [comment]
Updated text
